In [1]:
import pandas as pd

In [ ]:
"""
1. Creating Pandas Series Object
2. Creating Pandas DataFrame object
3. Indexing & Slicing of Series and DF
"""

In [2]:
names =['riya', 'rajiv', 'richa', 'ram']
series_n = pd.Series(names)
series_n

0     riya
1    rajiv
2    richa
3      ram
dtype: object

In [3]:
series_n.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
series_n.values

array(['riya', 'rajiv', 'richa', 'ram'], dtype=object)

In [5]:
count = {'USA' : 50, 'India': 500, 'UK' : 80, 'France': 90}
count = pd.Series(count)
count

USA        50
India     500
UK         80
France     90
dtype: int64

In [6]:
count.loc['India']

500

In [7]:
count.iloc[1]

500

In [8]:
head = {'USA' : 'NYC', 'India': 'Pune', 'UK' : 'London', 'France': 'Paris'}
head = pd.Series(head)
head

USA          NYC
India       Pune
UK        London
France     Paris
dtype: object

In [9]:
#combinng series data
df = pd.DataFrame({'Head Office': head, 'Employee Count': count})
df

       Head Office  Employee Count
USA            NYC              50
India         Pune             500
UK          London              80
France       Paris              90

In [10]:
df.loc['UK']

Head Office       London
Employee Count        80
Name: UK, dtype: object

In [11]:
df.loc[['UK', 'France']]

       Head Office  Employee Count
UK          London              80
France       Paris              90

In [13]:
df.loc['India': 'France']

       Head Office  Employee Count
India         Pune             500
UK          London              80
France       Paris              90

In [15]:
df.loc['India': 'France','Employee Count']

India     500
UK         80
France     90
Name: Employee Count, dtype: int64

In [16]:
df.loc['India': 'France', 'Head Office':'Employee Count']

       Head Office  Employee Count
India         Pune             500
UK          London              80
France       Paris              90

In [17]:
df.loc['India': 'France', 'Head Office':'Employee Count']

       Head Office  Employee Count
India         Pune             500
UK          London              80
France       Paris              90

In [18]:
df.loc['India': 'France', ['Head Office','Employee Count']]

       Head Office  Employee Count
India         Pune             500
UK          London              80
France       Paris              90

In [20]:
df.iloc[1:3, [0,1]]

      Head Office  Employee Count
India        Pune             500
UK         London              80

In [21]:
data = {'Name' : ['Riya', 'Rajiv', 'Richa', 'Ram'],
       'Salary': [300000, 400000, 200000, 500000],
       'Dept' : ['Admin', 'IT', 'IT', 'HR']}
df = pd.DataFrame(data)
df

    Name  Salary   Dept
0   riya  300000  Admin
1  rajiv  400000     IT
2  richa  200000     IT
3    ram  500000     HR

In [24]:
df=df.set_index('Name')
df

       Salary   Dept
Name
riya   300000  Admin
rajiv  400000     IT
richa  200000     IT
ram    500000     HR

In [25]:
# data - row data, index = labelled indices, columns = Col header
df= pd.DataFrame(data=[[500,35,23],[600,40,22],[300,25,25]],
                index=['Tata', 'Maruti', 'Honda'],
                columns=['Revenue', 'Market Share', 'Profit'])
df

        Revenue  Market Share  Profit
Tata        500            35      23
Maruti      600            40      22
Honda       300            25      25