In [1]:
import pandas as pd

In [ ]:
"""
1. sort_values(by=, ascending=)
2. nlargest()
3. nsmallest()
4. sort_index()
"""

In [2]:
df = pd.read_csv('Data.tsv', delimiter='\t')
df

,Name,Position,Office,Age,Start date,Salary
0,Airi Satou,Accountant,Tokyo,33,2008-11-28,"$162,700"
1,Angelica Ramos,Chief Executive Officer (CEO),London,47,2009-10-09,"$1,200,000"
2,Ashton Cox,Junior Technical Author,San Francisco,66,2009-01-12,"$86,000"
3,Bradley Greer,Software Engineer,London,41,2012-10-13,"$132,000"
4,Brenden Wagner,Software Engineer,San Francisco,28,2011-06-07,"$206,850"
5,Brielle Williamson,Integration Specialist,New York,61,2012-12-02,"$372,000"
6,Bruno Nash,Software Engineer,London,38,2011-05-03,"$163,500"
7,Caesar Vance,Pre-Sales Support,New York,21,2011-12-12,"$106,450"
8,Cara Stevens,Sales Assistant,New York,46,2011-12-06,"$145,600"
9,Cedric Kelly,Senior Javascript Developer,Edinburgh,22,2012-03-29,"$433,060"
10,Charde Marshall,Regional Director,San Francisco,36,2008-10-16,"$470,600"
11,Colleen Hurst,Javascript Developer,San Francisco,39,2009-09-15,"$205,500"
12,Dai Rios,Personnel Lead,Edinburgh,35,2012-09-26,"$217,500"
13,Donna Snider,Customer Support,New York,27,2011-01-25,"$112,000"
14,Doris Wilder,Sales Assistant,Sydney,23,2010-09-20,"$85,600"
15,Finn Camacho,Support Engineer,San Francisco,47,2009-07-07,"$87,500"
16,Fiona Green,Chief Operating Officer (COO),San Francisco,48,2010-03-11,"$850,000"
17,Garrett Winters,Accountant,Tokyo,63,2011-07-25,"$170,750"
18,Gavin Cortez,Team Leader,San Francisco,22,2008-10-26,"$235,500"
19,Gavin Joyce,Developer,Edinburgh,42,2010-12-22,"$92,575"
20,Gloria Little,Systems Administrator,New York,59,2009-04-10,"$237,500"
21,Haley Kennedy,Senior Marketing Designer,London,43,2012-12-18,"$313,500"
22,Hermione Butler,Regional Director,London,47,2011-03-21,"$356,250"
23,Herrod Chandler,Sales Assistant,San Francisco,59,2012-08-06,"$137,500"
24,Hope Fuentes,Secretary,San Francisco,41,2010-02-12,"$109,850"
25,Howard Hatfield,Office Manager,San Francisco,51,2008-12-16,"$164,500"
26,Jackson Bradshaw,Director,New York,65,2008-09-26,"$645,750"
27,Jena Gaines,Office Manager,London,30,2008-12-19,"$90,560"
28,Jenette Caldwell,Development Lead,New York,30,2011-09-03,"$345,000"
29,Jennifer Acosta,Junior Javascript Developer,Edinburgh,43,2013-02-01,"$75,650"
30,Jennifer Chang,Regional Director,Singapore,28,2010-11-14,"$357,650"
31,Jonas Alexander,Developer,San Francisco,30,2010-07-14,"$86,500"
32,Lael Greer,Systems Administrator,London,21,2009-02-27,"$103,500"
33,Martena Mccray,Post-Sales support,Edinburgh,46,2011-03-09,"$324,050"
34,Michael Bruce,Javascript Developer,Singapore,29,2011-06-27,"$183,000"
35,Michael Silva,Marketing Designer,London,66,2012-11-27,"$198,500"
36,Michelle House,Integration Specialist,Sydney,37,2011-06-02,"$95,400"
37,Olivia Liang,Support Engineer,Singapore,64,2011-02-03,"$234,500"
38,Paul Byrd,Chief Financial Officer (CFO),New York,64,2010-06-09,"$725,000"
39,Prescott Bartlett,Technical Author,London,27,2011-05-07,"$145,000"
40,Quinn Flynn,Support Lead,Edinburgh,22,2013-03-03,"$342,000"
41,Rhona Davidson,Integration Specialist,Tokyo,55,2010-10-14,"$327,900"
42,Sakura Yamamoto,Support Engineer,Tokyo,37,2009-08-19,"$139,575"
43,Serge Baldwin,Data Coordinator,Singapore,64,2012-04-09,"$138,575"
44,Shad Decker,Regional Director,Edinburgh,51,2008-11-13,"$183,000"
45,Shou Itou,Regional Marketing,Tokyo,20,2011-08-14,"$163,000"
46,Sonya Frost,Software Engineer,Edinburgh,23,2008-12-13,"$103,600"
47,Suki Burks,Developer,London,53,2009-10-22,"$114,500"
48,Tatyana Fitzpatrick,Regional Director,London,19,2010-03-17,"$385,750"
49,Thor Walton,Developer,New York,61,2013-08-11,"$98,540"
50,Tiger Nixon,System Architect,Edinburgh,61,2011-04-25,"$320,800"
51,Timothy Mooney,Office Manager,London,37,2008-12-11,"$136,200"
52,Unity Butler,Marketing Designer,San Francisco,47,2009-12-09,"$85,675"
53,Vivian Harrell,Financial Controller,San Francisco,62,2009-02-14,"$452,500"
54,Yuri Berry,Chief Marketing Officer (CMO),New York,40,2009-06-25,"$675,000"
55,Zenaida Frank,Software Engineer,New York,63,2010-01-04,"$125,250"
56,Zorita Serrano,Software Engineer,San Francisco,56,2012-06-01,"$115,000"
57,Name,Position,Office,Age,Start date,Salary

In [3]:
df.sort_values(by='Age')

,Name,Position,Office,Age,Start date,Salary
48,Tatyana Fitzpatrick,Regional Director,London,19,2010-03-17,"$385,750"
45,Shou Itou,Regional Marketing,Tokyo,20,2011-08-14,"$163,000"
7,Caesar Vance,Pre-Sales Support,New York,21,2011-12-12,"$106,450"
32,Lael Greer,Systems Administrator,London,21,2009-02-27,"$103,500"
18,Gavin Cortez,Team Leader,San Francisco,22,2008-10-26,"$235,500"
40,Quinn Flynn,Support Lead,Edinburgh,22,2013-03-03,"$342,000"
9,Cedric Kelly,Senior Javascript Developer,Edinburgh,22,2012-03-29,"$433,060"
46,Sonya Frost,Software Engineer,Edinburgh,23,2008-12-13,"$103,600"
14,Doris Wilder,Sales Assistant,Sydney,23,2010-09-20,"$85,600"
39,Prescott Bartlett,Technical Author,London,27,2011-05-07,"$145,000"
13,Donna Snider,Customer Support,New York,27,2011-01-25,"$112,000"
4,Brenden Wagner,Software Engineer,San Francisco,28,2011-06-07,"$206,850"
30,Jennifer Chang,Regional Director,Singapore,28,2010-11-14,"$357,650"
34,Michael Bruce,Javascript Developer,Singapore,29,2011-06-27,"$183,000"
27,Jena Gaines,Office Manager,London,30,2008-12-19,"$90,560"
31,Jonas Alexander,Developer,San Francisco,30,2010-07-14,"$86,500"
28,Jenette Caldwell,Development Lead,New York,30,2011-09-03,"$345,000"
0,Airi Satou,Accountant,Tokyo,33,2008-11-28,"$162,700"
12,Dai Rios,Personnel Lead,Edinburgh,35,2012-09-26,"$217,500"
10,Charde Marshall,Regional Director,San Francisco,36,2008-10-16,"$470,600"
36,Michelle House,Integration Specialist,Sydney,37,2011-06-02,"$95,400"
51,Timothy Mooney,Office Manager,London,37,2008-12-11,"$136,200"
42,Sakura Yamamoto,Support Engineer,Tokyo,37,2009-08-19,"$139,575"
6,Bruno Nash,Software Engineer,London,38,2011-05-03,"$163,500"
11,Colleen Hurst,Javascript Developer,San Francisco,39,2009-09-15,"$205,500"
54,Yuri Berry,Chief Marketing Officer (CMO),New York,40,2009-06-25,"$675,000"
24,Hope Fuentes,Secretary,San Francisco,41,2010-02-12,"$109,850"
3,Bradley Greer,Software Engineer,London,41,2012-10-13,"$132,000"
19,Gavin Joyce,Developer,Edinburgh,42,2010-12-22,"$92,575"
21,Haley Kennedy,Senior Marketing Designer,London,43,2012-12-18,"$313,500"
29,Jennifer Acosta,Junior Javascript Developer,Edinburgh,43,2013-02-01,"$75,650"
33,Martena Mccray,Post-Sales support,Edinburgh,46,2011-03-09,"$324,050"
8,Cara Stevens,Sales Assistant,New York,46,2011-12-06,"$145,600"
22,Hermione Butler,Regional Director,London,47,2011-03-21,"$356,250"
1,Angelica Ramos,Chief Executive Officer (CEO),London,47,2009-10-09,"$1,200,000"
52,Unity Butler,Marketing Designer,San Francisco,47,2009-12-09,"$85,675"
15,Finn Camacho,Support Engineer,San Francisco,47,2009-07-07,"$87,500"
16,Fiona Green,Chief Operating Officer (COO),San Francisco,48,2010-03-11,"$850,000"
44,Shad Decker,Regional Director,Edinburgh,51,2008-11-13,"$183,000"
25,Howard Hatfield,Office Manager,San Francisco,51,2008-12-16,"$164,500"
47,Suki Burks,Developer,London,53,2009-10-22,"$114,500"
41,Rhona Davidson,Integration Specialist,Tokyo,55,2010-10-14,"$327,900"
56,Zorita Serrano,Software Engineer,San Francisco,56,2012-06-01,"$115,000"
23,Herrod Chandler,Sales Assistant,San Francisco,59,2012-08-06,"$137,500"
20,Gloria Little,Systems Administrator,New York,59,2009-04-10,"$237,500"
49,Thor Walton,Developer,New York,61,2013-08-11,"$98,540"
5,Brielle Williamson,Integration Specialist,New York,61,2012-12-02,"$372,000"
50,Tiger Nixon,System Architect,Edinburgh,61,2011-04-25,"$320,800"
53,Vivian Harrell,Financial Controller,San Francisco,62,2009-02-14,"$452,500"
55,Zenaida Frank,Software Engineer,New York,63,2010-01-04,"$125,250"
17,Garrett Winters,Accountant,Tokyo,63,2011-07-25,"$170,750"
37,Olivia Liang,Support Engineer,Singapore,64,2011-02-03,"$234,500"
43,Serge Baldwin,Data Coordinator,Singapore,64,2012-04-09,"$138,575"
38,Paul Byrd,Chief Financial Officer (CFO),New York,64,2010-06-09,"$725,000"
26,Jackson Bradshaw,Director,New York,65,2008-09-26,"$645,750"
35,Michael Silva,Marketing Designer,London,66,2012-11-27,"$198,500"
2,Ashton Cox,Junior Technical Author,San Francisco,66,2009-01-12,"$86,000"
57,Name,Position,Office,Age,Start date,Salary

In [4]:
df.sort_values(by='Age',ascending=False )

,Name,Position,Office,Age,Start date,Salary
57,Name,Position,Office,Age,Start date,Salary
35,Michael Silva,Marketing Designer,London,66,2012-11-27,"$198,500"
2,Ashton Cox,Junior Technical Author,San Francisco,66,2009-01-12,"$86,000"
26,Jackson Bradshaw,Director,New York,65,2008-09-26,"$645,750"
43,Serge Baldwin,Data Coordinator,Singapore,64,2012-04-09,"$138,575"
37,Olivia Liang,Support Engineer,Singapore,64,2011-02-03,"$234,500"
38,Paul Byrd,Chief Financial Officer (CFO),New York,64,2010-06-09,"$725,000"
17,Garrett Winters,Accountant,Tokyo,63,2011-07-25,"$170,750"
55,Zenaida Frank,Software Engineer,New York,63,2010-01-04,"$125,250"
53,Vivian Harrell,Financial Controller,San Francisco,62,2009-02-14,"$452,500"
50,Tiger Nixon,System Architect,Edinburgh,61,2011-04-25,"$320,800"
5,Brielle Williamson,Integration Specialist,New York,61,2012-12-02,"$372,000"
49,Thor Walton,Developer,New York,61,2013-08-11,"$98,540"
23,Herrod Chandler,Sales Assistant,San Francisco,59,2012-08-06,"$137,500"
20,Gloria Little,Systems Administrator,New York,59,2009-04-10,"$237,500"
56,Zorita Serrano,Software Engineer,San Francisco,56,2012-06-01,"$115,000"
41,Rhona Davidson,Integration Specialist,Tokyo,55,2010-10-14,"$327,900"
47,Suki Burks,Developer,London,53,2009-10-22,"$114,500"
44,Shad Decker,Regional Director,Edinburgh,51,2008-11-13,"$183,000"
25,Howard Hatfield,Office Manager,San Francisco,51,2008-12-16,"$164,500"
16,Fiona Green,Chief Operating Officer (COO),San Francisco,48,2010-03-11,"$850,000"
22,Hermione Butler,Regional Director,London,47,2011-03-21,"$356,250"
52,Unity Butler,Marketing Designer,San Francisco,47,2009-12-09,"$85,675"
1,Angelica Ramos,Chief Executive Officer (CEO),London,47,2009-10-09,"$1,200,000"
15,Finn Camacho,Support Engineer,San Francisco,47,2009-07-07,"$87,500"
8,Cara Stevens,Sales Assistant,New York,46,2011-12-06,"$145,600"
33,Martena Mccray,Post-Sales support,Edinburgh,46,2011-03-09,"$324,050"
29,Jennifer Acosta,Junior Javascript Developer,Edinburgh,43,2013-02-01,"$75,650"
21,Haley Kennedy,Senior Marketing Designer,London,43,2012-12-18,"$313,500"
19,Gavin Joyce,Developer,Edinburgh,42,2010-12-22,"$92,575"
3,Bradley Greer,Software Engineer,London,41,2012-10-13,"$132,000"
24,Hope Fuentes,Secretary,San Francisco,41,2010-02-12,"$109,850"
54,Yuri Berry,Chief Marketing Officer (CMO),New York,40,2009-06-25,"$675,000"
11,Colleen Hurst,Javascript Developer,San Francisco,39,2009-09-15,"$205,500"
6,Bruno Nash,Software Engineer,London,38,2011-05-03,"$163,500"
42,Sakura Yamamoto,Support Engineer,Tokyo,37,2009-08-19,"$139,575"
51,Timothy Mooney,Office Manager,London,37,2008-12-11,"$136,200"
36,Michelle House,Integration Specialist,Sydney,37,2011-06-02,"$95,400"
10,Charde Marshall,Regional Director,San Francisco,36,2008-10-16,"$470,600"
12,Dai Rios,Personnel Lead,Edinburgh,35,2012-09-26,"$217,500"
0,Airi Satou,Accountant,Tokyo,33,2008-11-28,"$162,700"
27,Jena Gaines,Office Manager,London,30,2008-12-19,"$90,560"
28,Jenette Caldwell,Development Lead,New York,30,2011-09-03,"$345,000"
31,Jonas Alexander,Developer,San Francisco,30,2010-07-14,"$86,500"
34,Michael Bruce,Javascript Developer,Singapore,29,2011-06-27,"$183,000"
4,Brenden Wagner,Software Engineer,San Francisco,28,2011-06-07,"$206,850"
30,Jennifer Chang,Regional Director,Singapore,28,2010-11-14,"$357,650"
39,Prescott Bartlett,Technical Author,London,27,2011-05-07,"$145,000"
13,Donna Snider,Customer Support,New York,27,2011-01-25,"$112,000"
14,Doris Wilder,Sales Assistant,Sydney,23,2010-09-20,"$85,600"
46,Sonya Frost,Software Engineer,Edinburgh,23,2008-12-13,"$103,600"
40,Quinn Flynn,Support Lead,Edinburgh,22,2013-03-03,"$342,000"
18,Gavin Cortez,Team Leader,San Francisco,22,2008-10-26,"$235,500"
9,Cedric Kelly,Senior Javascript Developer,Edinburgh,22,2012-03-29,"$433,060"
7,Caesar Vance,Pre-Sales Support,New York,21,2011-12-12,"$106,450"
32,Lael Greer,Systems Administrator,London,21,2009-02-27,"$103,500"
45,Shou Itou,Regional Marketing,Tokyo,20,2011-08-14,"$163,000"
48,Tatyana Fitzpatrick,Regional Director,London,19,2010-03-17,"$385,750"

In [5]:
df.sort_values(by=['Name','Age'], ascending= [True,False])

,Name,Position,Office,Age,Start date,Salary
0,Airi Satou,Accountant,Tokyo,33,2008-11-28,"$162,700"
1,Angelica Ramos,Chief Executive Officer (CEO),London,47,2009-10-09,"$1,200,000"
2,Ashton Cox,Junior Technical Author,San Francisco,66,2009-01-12,"$86,000"
3,Bradley Greer,Software Engineer,London,41,2012-10-13,"$132,000"
4,Brenden Wagner,Software Engineer,San Francisco,28,2011-06-07,"$206,850"
5,Brielle Williamson,Integration Specialist,New York,61,2012-12-02,"$372,000"
6,Bruno Nash,Software Engineer,London,38,2011-05-03,"$163,500"
7,Caesar Vance,Pre-Sales Support,New York,21,2011-12-12,"$106,450"
8,Cara Stevens,Sales Assistant,New York,46,2011-12-06,"$145,600"
9,Cedric Kelly,Senior Javascript Developer,Edinburgh,22,2012-03-29,"$433,060"
10,Charde Marshall,Regional Director,San Francisco,36,2008-10-16,"$470,600"
11,Colleen Hurst,Javascript Developer,San Francisco,39,2009-09-15,"$205,500"
12,Dai Rios,Personnel Lead,Edinburgh,35,2012-09-26,"$217,500"
13,Donna Snider,Customer Support,New York,27,2011-01-25,"$112,000"
14,Doris Wilder,Sales Assistant,Sydney,23,2010-09-20,"$85,600"
15,Finn Camacho,Support Engineer,San Francisco,47,2009-07-07,"$87,500"
16,Fiona Green,Chief Operating Officer (COO),San Francisco,48,2010-03-11,"$850,000"
17,Garrett Winters,Accountant,Tokyo,63,2011-07-25,"$170,750"
18,Gavin Cortez,Team Leader,San Francisco,22,2008-10-26,"$235,500"
19,Gavin Joyce,Developer,Edinburgh,42,2010-12-22,"$92,575"
20,Gloria Little,Systems Administrator,New York,59,2009-04-10,"$237,500"
21,Haley Kennedy,Senior Marketing Designer,London,43,2012-12-18,"$313,500"
22,Hermione Butler,Regional Director,London,47,2011-03-21,"$356,250"
23,Herrod Chandler,Sales Assistant,San Francisco,59,2012-08-06,"$137,500"
24,Hope Fuentes,Secretary,San Francisco,41,2010-02-12,"$109,850"
25,Howard Hatfield,Office Manager,San Francisco,51,2008-12-16,"$164,500"
26,Jackson Bradshaw,Director,New York,65,2008-09-26,"$645,750"
27,Jena Gaines,Office Manager,London,30,2008-12-19,"$90,560"
28,Jenette Caldwell,Development Lead,New York,30,2011-09-03,"$345,000"
29,Jennifer Acosta,Junior Javascript Developer,Edinburgh,43,2013-02-01,"$75,650"
30,Jennifer Chang,Regional Director,Singapore,28,2010-11-14,"$357,650"
31,Jonas Alexander,Developer,San Francisco,30,2010-07-14,"$86,500"
32,Lael Greer,Systems Administrator,London,21,2009-02-27,"$103,500"
33,Martena Mccray,Post-Sales support,Edinburgh,46,2011-03-09,"$324,050"
34,Michael Bruce,Javascript Developer,Singapore,29,2011-06-27,"$183,000"
35,Michael Silva,Marketing Designer,London,66,2012-11-27,"$198,500"
36,Michelle House,Integration Specialist,Sydney,37,2011-06-02,"$95,400"
57,Name,Position,Office,Age,Start date,Salary
37,Olivia Liang,Support Engineer,Singapore,64,2011-02-03,"$234,500"
38,Paul Byrd,Chief Financial Officer (CFO),New York,64,2010-06-09,"$725,000"
39,Prescott Bartlett,Technical Author,London,27,2011-05-07,"$145,000"
40,Quinn Flynn,Support Lead,Edinburgh,22,2013-03-03,"$342,000"
41,Rhona Davidson,Integration Specialist,Tokyo,55,2010-10-14,"$327,900"
42,Sakura Yamamoto,Support Engineer,Tokyo,37,2009-08-19,"$139,575"
43,Serge Baldwin,Data Coordinator,Singapore,64,2012-04-09,"$138,575"
44,Shad Decker,Regional Director,Edinburgh,51,2008-11-13,"$183,000"
45,Shou Itou,Regional Marketing,Tokyo,20,2011-08-14,"$163,000"
46,Sonya Frost,Software Engineer,Edinburgh,23,2008-12-13,"$103,600"
47,Suki Burks,Developer,London,53,2009-10-22,"$114,500"
48,Tatyana Fitzpatrick,Regional Director,London,19,2010-03-17,"$385,750"
49,Thor Walton,Developer,New York,61,2013-08-11,"$98,540"
50,Tiger Nixon,System Architect,Edinburgh,61,2011-04-25,"$320,800"
51,Timothy Mooney,Office Manager,London,37,2008-12-11,"$136,200"
52,Unity Butler,Marketing Designer,San Francisco,47,2009-12-09,"$85,675"
53,Vivian Harrell,Financial Controller,San Francisco,62,2009-02-14,"$452,500"
54,Yuri Berry,Chief Marketing Officer (CMO),New York,40,2009-06-25,"$675,000"
55,Zenaida Frank,Software Engineer,New York,63,2010-01-04,"$125,250"
56,Zorita Serrano,Software Engineer,San Francisco,56,2012-06-01,"$115,000"

In [15]:
df['Age'].dtype

dtype('O')

In [18]:
df['Age']=df['Age'].astype(float)

In [19]:
df.nlargest(10, 'Age')

,Name,Position,Office,Age,Start date,Salary
2,Ashton Cox,Junior Technical Author,San Francisco,66.0,2009-01-12,"$86,000"
35,Michael Silva,Marketing Designer,London,66.0,2012-11-27,"$198,500"
26,Jackson Bradshaw,Director,New York,65.0,2008-09-26,"$645,750"
37,Olivia Liang,Support Engineer,Singapore,64.0,2011-02-03,"$234,500"
38,Paul Byrd,Chief Financial Officer (CFO),New York,64.0,2010-06-09,"$725,000"
43,Serge Baldwin,Data Coordinator,Singapore,64.0,2012-04-09,"$138,575"
17,Garrett Winters,Accountant,Tokyo,63.0,2011-07-25,"$170,750"
55,Zenaida Frank,Software Engineer,New York,63.0,2010-01-04,"$125,250"
53,Vivian Harrell,Financial Controller,San Francisco,62.0,2009-02-14,"$452,500"
5,Brielle Williamson,Integration Specialist,New York,61.0,2012-12-02,"$372,000"

In [20]:
df.nsmallest(10, 'Age')

,Name,Position,Office,Age,Start date,Salary
57,Name,Position,Office,0.0,Start date,Salary
48,Tatyana Fitzpatrick,Regional Director,London,19.0,2010-03-17,"$385,750"
45,Shou Itou,Regional Marketing,Tokyo,20.0,2011-08-14,"$163,000"
7,Caesar Vance,Pre-Sales Support,New York,21.0,2011-12-12,"$106,450"
32,Lael Greer,Systems Administrator,London,21.0,2009-02-27,"$103,500"
9,Cedric Kelly,Senior Javascript Developer,Edinburgh,22.0,2012-03-29,"$433,060"
18,Gavin Cortez,Team Leader,San Francisco,22.0,2008-10-26,"$235,500"
40,Quinn Flynn,Support Lead,Edinburgh,22.0,2013-03-03,"$342,000"
14,Doris Wilder,Sales Assistant,Sydney,23.0,2010-09-20,"$85,600"
46,Sonya Frost,Software Engineer,Edinburgh,23.0,2008-12-13,"$103,600"

In [21]:
df = pd.read_csv('Data.tsv', delimiter='\t', index_col='Office')
df

,Name,Position,Age,Start date,Salary
Office,,,,,
Tokyo,Airi Satou,Accountant,33,2008-11-28,"$162,700"
London,Angelica Ramos,Chief Executive Officer (CEO),47,2009-10-09,"$1,200,000"
San Francisco,Ashton Cox,Junior Technical Author,66,2009-01-12,"$86,000"
London,Bradley Greer,Software Engineer,41,2012-10-13,"$132,000"
San Francisco,Brenden Wagner,Software Engineer,28,2011-06-07,"$206,850"
New York,Brielle Williamson,Integration Specialist,61,2012-12-02,"$372,000"
London,Bruno Nash,Software Engineer,38,2011-05-03,"$163,500"
New York,Caesar Vance,Pre-Sales Support,21,2011-12-12,"$106,450"
New York,Cara Stevens,Sales Assistant,46,2011-12-06,"$145,600"
Edinburgh,Cedric Kelly,Senior Javascript Developer,22,2012-03-29,"$433,060"
San Francisco,Charde Marshall,Regional Director,36,2008-10-16,"$470,600"
San Francisco,Colleen Hurst,Javascript Developer,39,2009-09-15,"$205,500"
Edinburgh,Dai Rios,Personnel Lead,35,2012-09-26,"$217,500"
New York,Donna Snider,Customer Support,27,2011-01-25,"$112,000"
Sydney,Doris Wilder,Sales Assistant,23,2010-09-20,"$85,600"
San Francisco,Finn Camacho,Support Engineer,47,2009-07-07,"$87,500"
San Francisco,Fiona Green,Chief Operating Officer (COO),48,2010-03-11,"$850,000"
Tokyo,Garrett Winters,Accountant,63,2011-07-25,"$170,750"
San Francisco,Gavin Cortez,Team Leader,22,2008-10-26,"$235,500"
Edinburgh,Gavin Joyce,Developer,42,2010-12-22,"$92,575"
New York,Gloria Little,Systems Administrator,59,2009-04-10,"$237,500"
London,Haley Kennedy,Senior Marketing Designer,43,2012-12-18,"$313,500"
London,Hermione Butler,Regional Director,47,2011-03-21,"$356,250"
San Francisco,Herrod Chandler,Sales Assistant,59,2012-08-06,"$137,500"
San Francisco,Hope Fuentes,Secretary,41,2010-02-12,"$109,850"
San Francisco,Howard Hatfield,Office Manager,51,2008-12-16,"$164,500"
New York,Jackson Bradshaw,Director,65,2008-09-26,"$645,750"
London,Jena Gaines,Office Manager,30,2008-12-19,"$90,560"
New York,Jenette Caldwell,Development Lead,30,2011-09-03,"$345,000"
Edinburgh,Jennifer Acosta,Junior Javascript Developer,43,2013-02-01,"$75,650"
Singapore,Jennifer Chang,Regional Director,28,2010-11-14,"$357,650"
San Francisco,Jonas Alexander,Developer,30,2010-07-14,"$86,500"
London,Lael Greer,Systems Administrator,21,2009-02-27,"$103,500"
Edinburgh,Martena Mccray,Post-Sales support,46,2011-03-09,"$324,050"
Singapore,Michael Bruce,Javascript Developer,29,2011-06-27,"$183,000"
London,Michael Silva,Marketing Designer,66,2012-11-27,"$198,500"
Sydney,Michelle House,Integration Specialist,37,2011-06-02,"$95,400"
Singapore,Olivia Liang,Support Engineer,64,2011-02-03,"$234,500"
New York,Paul Byrd,Chief Financial Officer (CFO),64,2010-06-09,"$725,000"
London,Prescott Bartlett,Technical Author,27,2011-05-07,"$145,000"
Edinburgh,Quinn Flynn,Support Lead,22,2013-03-03,"$342,000"
Tokyo,Rhona Davidson,Integration Specialist,55,2010-10-14,"$327,900"
Tokyo,Sakura Yamamoto,Support Engineer,37,2009-08-19,"$139,575"
Singapore,Serge Baldwin,Data Coordinator,64,2012-04-09,"$138,575"
Edinburgh,Shad Decker,Regional Director,51,2008-11-13,"$183,000"
Tokyo,Shou Itou,Regional Marketing,20,2011-08-14,"$163,000"
Edinburgh,Sonya Frost,Software Engineer,23,2008-12-13,"$103,600"
London,Suki Burks,Developer,53,2009-10-22,"$114,500"
London,Tatyana Fitzpatrick,Regional Director,19,2010-03-17,"$385,750"
New York,Thor Walton,Developer,61,2013-08-11,"$98,540"
Edinburgh,Tiger Nixon,System Architect,61,2011-04-25,"$320,800"
London,Timothy Mooney,Office Manager,37,2008-12-11,"$136,200"
San Francisco,Unity Butler,Marketing Designer,47,2009-12-09,"$85,675"
San Francisco,Vivian Harrell,Financial Controller,62,2009-02-14,"$452,500"
New York,Yuri Berry,Chief Marketing Officer (CMO),40,2009-06-25,"$675,000"
New York,Zenaida Frank,Software Engineer,63,2010-01-04,"$125,250"
San Francisco,Zorita Serrano,Software Engineer,56,2012-06-01,"$115,000"
Office,Name,Position,Age,Start date,Salary

In [22]:
df.sort_index()

,Name,Position,Age,Start date,Salary
Office,,,,,
Edinburgh,Jennifer Acosta,Junior Javascript Developer,43,2013-02-01,"$75,650"
Edinburgh,Quinn Flynn,Support Lead,22,2013-03-03,"$342,000"
Edinburgh,Gavin Joyce,Developer,42,2010-12-22,"$92,575"
Edinburgh,Cedric Kelly,Senior Javascript Developer,22,2012-03-29,"$433,060"
Edinburgh,Shad Decker,Regional Director,51,2008-11-13,"$183,000"
Edinburgh,Tiger Nixon,System Architect,61,2011-04-25,"$320,800"
Edinburgh,Dai Rios,Personnel Lead,35,2012-09-26,"$217,500"
Edinburgh,Sonya Frost,Software Engineer,23,2008-12-13,"$103,600"
Edinburgh,Martena Mccray,Post-Sales support,46,2011-03-09,"$324,050"
London,Tatyana Fitzpatrick,Regional Director,19,2010-03-17,"$385,750"
London,Michael Silva,Marketing Designer,66,2012-11-27,"$198,500"
London,Jena Gaines,Office Manager,30,2008-12-19,"$90,560"
London,Prescott Bartlett,Technical Author,27,2011-05-07,"$145,000"
London,Hermione Butler,Regional Director,47,2011-03-21,"$356,250"
London,Haley Kennedy,Senior Marketing Designer,43,2012-12-18,"$313,500"
London,Suki Burks,Developer,53,2009-10-22,"$114,500"
London,Lael Greer,Systems Administrator,21,2009-02-27,"$103,500"
London,Timothy Mooney,Office Manager,37,2008-12-11,"$136,200"
London,Bruno Nash,Software Engineer,38,2011-05-03,"$163,500"
London,Bradley Greer,Software Engineer,41,2012-10-13,"$132,000"
London,Angelica Ramos,Chief Executive Officer (CEO),47,2009-10-09,"$1,200,000"
New York,Donna Snider,Customer Support,27,2011-01-25,"$112,000"
New York,Cara Stevens,Sales Assistant,46,2011-12-06,"$145,600"
New York,Gloria Little,Systems Administrator,59,2009-04-10,"$237,500"
New York,Caesar Vance,Pre-Sales Support,21,2011-12-12,"$106,450"
New York,Brielle Williamson,Integration Specialist,61,2012-12-02,"$372,000"
New York,Yuri Berry,Chief Marketing Officer (CMO),40,2009-06-25,"$675,000"
New York,Paul Byrd,Chief Financial Officer (CFO),64,2010-06-09,"$725,000"
New York,Jackson Bradshaw,Director,65,2008-09-26,"$645,750"
New York,Zenaida Frank,Software Engineer,63,2010-01-04,"$125,250"
New York,Thor Walton,Developer,61,2013-08-11,"$98,540"
New York,Jenette Caldwell,Development Lead,30,2011-09-03,"$345,000"
Office,Name,Position,Age,Start date,Salary
San Francisco,Brenden Wagner,Software Engineer,28,2011-06-07,"$206,850"
San Francisco,Colleen Hurst,Javascript Developer,39,2009-09-15,"$205,500"
San Francisco,Finn Camacho,Support Engineer,47,2009-07-07,"$87,500"
San Francisco,Fiona Green,Chief Operating Officer (COO),48,2010-03-11,"$850,000"
San Francisco,Vivian Harrell,Financial Controller,62,2009-02-14,"$452,500"
San Francisco,Jonas Alexander,Developer,30,2010-07-14,"$86,500"
San Francisco,Gavin Cortez,Team Leader,22,2008-10-26,"$235,500"
San Francisco,Charde Marshall,Regional Director,36,2008-10-16,"$470,600"
San Francisco,Unity Butler,Marketing Designer,47,2009-12-09,"$85,675"
San Francisco,Herrod Chandler,Sales Assistant,59,2012-08-06,"$137,500"
San Francisco,Hope Fuentes,Secretary,41,2010-02-12,"$109,850"
San Francisco,Howard Hatfield,Office Manager,51,2008-12-16,"$164,500"
San Francisco,Zorita Serrano,Software Engineer,56,2012-06-01,"$115,000"
San Francisco,Ashton Cox,Junior Technical Author,66,2009-01-12,"$86,000"
Singapore,Serge Baldwin,Data Coordinator,64,2012-04-09,"$138,575"
Singapore,Olivia Liang,Support Engineer,64,2011-02-03,"$234,500"
Singapore,Michael Bruce,Javascript Developer,29,2011-06-27,"$183,000"
Singapore,Jennifer Chang,Regional Director,28,2010-11-14,"$357,650"
Sydney,Michelle House,Integration Specialist,37,2011-06-02,"$95,400"
Sydney,Doris Wilder,Sales Assistant,23,2010-09-20,"$85,600"
Tokyo,Shou Itou,Regional Marketing,20,2011-08-14,"$163,000"
Tokyo,Sakura Yamamoto,Support Engineer,37,2009-08-19,"$139,575"
Tokyo,Rhona Davidson,Integration Specialist,55,2010-10-14,"$327,900"
Tokyo,Garrett Winters,Accountant,63,2011-07-25,"$170,750"
Tokyo,Airi Satou,Accountant,33,2008-11-28,"$162,700"